package rules

// DefaultRules returns a curated set of universal code review rules.
// These apply when no user-defined rules are present.
func DefaultRules() []Rule {
	return []Rule{
		{
			ID:          "SEC-001",
			Title:       "Hardcoded Secrets",
			Description: "Detect hardcoded credentials, API keys, tokens, or passwords in source code. Secrets must be loaded from environment variables, vaults, or secret managers.",
			Severity:    "critical",
			Category:    "Security",
			Tags:        []string{"Security", "Secrets Management"},
		},
		{
			ID:          "SEC-002",
			Title:       "SQL Injection",
			Description: "Identify raw string concatenation or interpolation used to build SQL queries. Use parameterized queries or prepared statements instead.",
			Severity:    "critical",
			Category:    "Security",
			Tags:        []string{"Security", "Input Validation"},
		},
		{
			ID:          "SEC-003",
			Title:       "Command Injection",
			Description: "Flag shell command construction from unsanitized user input. Use parameterized execution APIs (e.g., exec.Command with separate args) instead of shell interpolation.",
			Severity:    "critical",
			Category:    "Security",
			Tags:        []string{"Security", "Input Validation"},
		},
		{
			ID:          "SEC-004",
			Title:       "Insecure Deserialization",
			Description: "Warn when untrusted input is deserialized without validation (e.g., pickle, yaml.Unsafe, eval). Restrict deserialization to safe loaders and validated schemas.",
			Severity:    "high",
			Category:    "Security",
			Tags:        []string{"Security", "Input Validation"},
		},
		{
			ID:          "ERR-001",
			Title:       "Swallowed Errors",
			Description: "Detect empty catch blocks, ignored error returns, or discarded error values. Errors must be handled, logged, or explicitly propagated.",
			Severity:    "high",
			Category:    "Error Handling",
			Tags:        []string{"Error Handling", "Reliability"},
		},
		{
			ID:          "ERR-002",
			Title:       "Panic in Library Code",
			Description: "Library and shared packages should return errors, not panic. Panics are reserved for truly unrecoverable states in main/top-level code only.",
			Severity:    "high",
			Category:    "Error Handling",
			Tags:        []string{"Error Handling", "API Design"},
		},
		{
			ID:          "ERR-003",
			Title:       "Missing Error Context",
			Description: "Errors propagated up the call stack should be wrapped with context (e.g., fmt.Errorf with %w) so the origin is traceable without a debugger.",
			Severity:    "medium",
			Category:    "Error Handling",
			Tags:        []string{"Error Handling", "Observability"},
		},
		{
			ID:          "PERF-001",
			Title:       "Unbounded Collection Growth",
			Description: "Detect slices, maps, or channels that grow without bounds (e.g., in-memory caches with no eviction, append in infinite loops). Enforce size limits or TTL.",
			Severity:    "high",
			Category:    "Performance",
			Tags:        []string{"Performance", "Reliability"},
		},
		{
			ID:          "PERF-002",
			Title:       "N+1 Query Pattern",
			Description: "Identify database or API calls executed inside loops that could be batched into a single query. Use bulk fetch, JOINs, or preloading instead.",
			Severity:    "medium",
			Category:    "Performance",
			Tags:        []string{"Performance", "Data Access"},
		},
		{
			ID:          "CONC-001",
			Title:       "Data Race Potential",
			Description: "Flag shared mutable state accessed from multiple goroutines/threads without synchronization (mutexes, channels, atomics).",
			Severity:    "high",
			Category:    "Concurrency",
			Tags:        []string{"Concurrency", "Reliability"},
		},
		{
			ID:          "LOG-001",
			Title:       "Sensitive Data in Logs",
			Description: "Detect logging of passwords, tokens, PII, or full request bodies. Log only safe identifiers; redact or omit sensitive fields.",
			Severity:    "high",
			Category:    "Observability",
			Tags:        []string{"Observability", "Security"},
		},
		{
			ID:          "LOG-002",
			Title:       "Debug Artifacts in Production Code",
			Description: "Flag TODO/FIXME/HACK comments, console.log, fmt.Println, print() statements, and other debug artifacts that should not ship.",
			Severity:    "low",
			Category:    "Observability",
			Tags:        []string{"Observability", "Code Quality"},
		},
		{
			ID:          "TEST-001",
			Title:       "Missing Error Case Tests",
			Description: "When new error paths are introduced, corresponding test cases for those error conditions should be present or added.",
			Severity:    "medium",
			Category:    "Testing",
			Tags:        []string{"Testing", "Reliability"},
		},
		{
			ID:          "API-001",
			Title:       "Breaking API Contract",
			Description: "Detect changes to public function signatures, REST endpoints, protobuf fields, or exported types that break backward compatibility without a version bump.",
			Severity:    "high",
			Category:    "API Design",
			Tags:        []string{"API Design", "Compatibility"},
		},
		{
			ID:          "RES-001",
			Title:       "Resource Leak",
			Description: "Detect opened files, connections, transactions, or locks that are not closed/released via defer, try-with-resources, context managers, or equivalent.",
			Severity:    "high",
			Category:    "Reliability",
			Tags:        []string{"Reliability", "Resource Management"},
		},
	}
}
